name: Build and publish mobile release
on:  
  push:
    tags:
      - '*'
env:
  android_artefact_name: pjsip-android-${{github.ref_name}}
  ios_artefact_name: pjsip-ios-${{github.ref_name}}
jobs:
  build-ios:
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build framework
        run: cd ios_framework && ./build_ios_framework.sh --source-dir=$(dirname "$(realpath "$PWD")") --output-dir="$PWD/artifact" --name="${{env.ios_artefact_name}}"
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ios-artifact
          path: ./ios_framework/artifact/${{env.ios_artefact_name}}.zip

  build-android:
    runs-on: ubuntu-latest
    container: 
      image: rinekri/pjsip-android-builder:latest
      volumes:
        - ${{ github.workspace }}/input:/home/tools/pjproject 
        - ${{ github.workspace }}/output:/home/output/pjsip-build-output
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: input
      - name: Build library
        run: |
          mkdir -p output
          cd /home
          ./build
      - name: Create asset 
        run: tar -czvf ${{env.android_artefact_name}}.tar.gz -C output .
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: android-artifact
          path: ./${{env.android_artefact_name}}.tar.gz
      
  create-release:
    needs: [build-ios, build-android]
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download all workflow artifacts
        uses: actions/download-artifact@v2
      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: Mobile release ${{ github.ref_name }}
          artifacts: ./ios-artifact/${{env.ios_artefact_name}}.zip, ./android-artifact/${{env.android_artefact_name}}.tar.gz
          draft: true
          prerelease: false



